### ISSUE TITLE
Setting up IMU with Ubuntu 22.04

### ISSUE THREAD

**Issue by mroglan** [gt-marine-robotics-group/Pontus#1]
The Lord Microstrain GX-3 IMU is an old IMU. We currently have a ROS Foxy driver that works with it on Ubuntu 20.04, but we have not been able to find a driver which works with it reliably in Ubuntu 22.04 (ROS Humble). The [microstrain inertial driver](https://github.com/LORD-MicroStrain/microstrain_inertial), which we use on Foxy, does not technically support the IMU (however it works on Foxy). We have not been able to get the driver to work consistently on Humble.

For this task, find a ROS Humble driver, or create one (likely using the [mscl package](https://github.com/LORD-MicroStrain/MSCL/tree/master)) which consistently streams data from our IMU.

**Comment by Jeff300fang** [comment]
Used the driver found here: [link](https://github.com/LORD-MicroStrain/microstrain_inertial/tree/ros2). Followed the normal installation steps using the build farm. 

Created a file named: "sensor_params.yml":

```                                                                            
microstrain_inertial_driver:
  ros__parameters:
    port : /dev/serial/by-id/usb-MicroStrain__Inc._3DM-GX3-25_Orientation_Sensor_6223.12899______-if00
    baudrate : 115200
```

In a terminal start the node:

```
ros2 launch microstrain_inertial_driver microstrain_launch.py params_file:="sensor_params.yml" configure:="true"
```

This will create the node and configure it. It will then set the node into an inactive state.

Then in another terminal run:

```
ros2 lifecycle set /microstrain_inertial_driver activate
```

This will activate the node. This node publishes the data to the node named
```
/imu/data
```

![Screenshot 2024-02-20 192904](https://github.com/gt-marine-robotics-group/Pontus/assets/25809159/d4b362b1-8abe-4a42-882d-2ef2b5f3889d)

**Comment by mroglan** [comment]
Awesome! Could you create an `imu.launch.py` file in `pontus_sensors` which launches the IMU driver for us, and add a `microstrain.yaml` file to the `config` directory with the parameters you specified? This is similar to how we launch the sensors in [Virtuoso](https://github.com/gt-marine-robotics-group/Virtuoso/tree/main/virtuoso_sensors). I will create a new GitHub issue for this as well.

**Comment by Jeff300fang** [comment]
Yup I'll look into it
