### ISSUE TITLE
Ethernet Communication

### ISSUE THREAD

**Issue by mroglan** [gt-marine-robotics-group/Pontus#4]
We need to communicate to the computer in our sub over Ethernet. For other competitions, we have SSHed to the computer over wifi, so ideally the process of SSHing over Ethernet will be similar. For this task, we would want to connect a NUC in the lab to some other laptop and SSH from that laptop into the NUC.

**Comment by belericant** [comment]
The easiest way to go about this is to run `sudo ip addr add 192.168.1.X/24 dev eth0` where `X` can be anything from 1 to 254 and `eth0` can be replaced by the actual name of the ethernet interface. Then on the laptop side you just need to statically configure your ip to be in the same subnet.

**Comment by mroglan** [comment]
How do you configure your laptop's ip to be the same subnet?

**Comment by belericant** [comment]
As long as you choose a static ip address in the same subnet on the laptop side you should be set. Of course, you could also do something more fancy like set up a DHCP server on the Orin side, but IMO not worth the effort.
